**MODEL BUILDING**

1)Add CNN layers

In [12]:
model=Sequential()
model.add(Conv2D(64,(3,3),input_shape=(28,28,1),activation='relu'))
model.add(Conv2D(32,(3,3),activation='relu'))

In [13]:
model.add(Flatten())
model.add(Dense(no_of_classes,activation='softmax'))

2)Compiling the model

In [14]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics='accuracy')

3)Train the model

In [16]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=5,batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 219s 117ms/step - loss: 0.1189 - accuracy: 0.9650 - val_loss: 0.0904 - val_accuracy: 0.9730
Epoch 2/5
1875/1875 [==============================] - 227s 121ms/step - loss: 0.0625 - accuracy: 0.9807 - val_loss: 0.0841 - val_accuracy: 0.9753
Epoch 3/5
1875/1875 [==============================] - 209s 112ms/step - loss: 0.0449 - accuracy: 0.9856 - val_loss: 0.0978 - val_accuracy: 0.9737
Epoch 4/5
1875/1875 [==============================] - 198s 106ms/step - loss: 0.0334 - accuracy: 0.9895 - val_loss: 0.0886 - val_accuracy: 0.9769
Epoch 5/5
1875/1875 [==============================] - 199s 106ms/step - loss: 0.0258 - accuracy: 0.9912 - val_loss: 0.1055 - val_accuracy: 0.9784


4)Observing the metrics

In [19]:
metrics=model.evaluate(x_test,y_test,verbose=0)
print("Test loss and Accuracy: ")
print(metrics)

Test loss and Accuracy: 
[0.1054532378911972, 0.9783999919891357]


5)Test the model

In [20]:
prediction=model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 0s 98ms/step
[[1.51065209e-13 6.44978494e-25 8.65963659e-14 3.26825962e-11
  9.47202940e-25 1.19114804e-18 1.28429745e-26 1.00000000e+00
  1.38301835e-15 8.26784455e-14]
 [1.31778583e-12 7.81938804e-15 1.00000000e+00 9.68105223e-18
  4.99522820e-21 5.18862822e-22 1.34380164e-13 2.48633281e-22
  2.61236426e-13 4.69462156e-22]
 [1.68172698e-09 9.99995112e-01 5.34883355e-08 5.99780919e-11
  4.23711890e-06 8.22161255e-08 1.89944838e-09 5.62873588e-08
  4.28927081e-07 1.08554459e-11]
 [1.00000000e+00 2.61482245e-24 2.43567861e-13 1.02484143e-19
  1.69990000e-18 1.52674599e-13 4.49064848e-11 5.47756249e-16
  2.84870224e-15 1.86999041e-10]]


In [21]:
print(np.argmax(prediction,axis=1))
print(y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


6)Save the model

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [23]:
cd /content/drive/MyDrive/Ibm

/content/drive/MyDrive/Ibm


In [24]:
model.save('mnistCNN.h5')

In [25]:
ls

flower_model.h5  flowers/  Flowers-Dataset/  mnistCNN.h5


7)Test with the saved model

In [60]:
model=load_model('mnistCNN.h5')

In [61]:
for index in range(4):
  img=Image.open('/content/sample_data/data/'+str(index)+".PNG").convert("L")
  img=img.resize((28,28))
  im2arr=np.array(img)
  im2arr=im2arr.reshape(1,28,28,1)
  y_pred=model.predict(im2arr)
  print(y_pred)

1/1 [==============================] - 0s 66ms/step
[[9.6982789e-01 8.0017298e-11 1.7484292e-02 1.2110131e-07 4.9013915e-03
  1.3137920e-08 3.1711286e-05 7.4076587e-03 7.4812192e-06 3.3949470e-04]]
1/1 [==============================] - 0s 19ms/step
[[1.6196250e-03 7.0740223e-01 1.4011368e-01 9.5595919e-07 1.5306512e-03
  3.2095194e-03 2.6291044e-02 5.3347758e-06 1.1982681e-01 3.6839186e-08]]
1/1 [==============================] - 0s 22ms/step
[[7.9126934e-11 2.3904523e-08 1.0000000e+00 5.2559366e-09 3.7665665e-12
  4.2872839e-09 5.1730562e-14 5.5101497e-09 1.9257273e-08 6.3589800e-09]]
1/1 [==============================] - 0s 20ms/step
[[7.4970056e-15 9.0065892e-11 1.4669507e-07 9.9997354e-01 3.3319944e-16
  2.1856363e-10 1.6070186e-15 2.6371266e-05 3.8795996e-08 1.4198370e-08]]
